/**
 * Protected Files Extension for {{PRODUCT}} CLI
 *
 * Manages a registry of governed data files and provides tools to add/remove entries.
 * When the registry changes, auto-regenerates the hookify rule pattern in
 * .github/hookflows/block-protected-files.md so the hookflow engine enforces blocking.
 *
 * Architecture:
 * - Hookflows (hookify .md) = enforcement layer (preToolUse blocks)
 * - This extension = management layer (add/remove tools + defense-in-depth onPostToolUse)
 * - onPreToolUse kept for future SDK versions that may dispatch it
 *
 * Registry: data/protected-files.json — JSON object mapping relative paths to denial messages.
 * Hot-reloads every 5 seconds via watchFile.
 *
 * ⚠️ LIMITATION: Hooks do NOT propagate to sub-agents (SDK v1.0.47).
 * Prompt-level enforcement in agent definitions is primary. This is defense-in-depth.
 */
import { readFileSync, writeFileSync, existsSync, watchFile } from "node:fs";
import { resolve, dirname } from "node:path";
import { joinSession } from "@github/copilot-sdk/extension";

const REPO_ROOT = resolve(
  dirname(import.meta.url.replace("file:///", "")),
  "..", "..", ".."
);

const REGISTRY_PATH = resolve(REPO_ROOT, "data", "protected-files.json");
const HOOKFLOW_PATH = resolve(
  REPO_ROOT,
  ".github",
  "hookflows",
  "block-protected-files.md"
);

// ── Registry loading with hot-reload ────────────────────────────────────────

let registry = {};

function loadRegistry() {
  try {
    if (!existsSync(REGISTRY_PATH)) {
      registry = {};
      return;
    }
    const raw = readFileSync(REGISTRY_PATH, "utf-8");
    const parsed = JSON.parse(raw);
    if (typeof parsed === "object" && parsed !== null && !Array.isArray(parsed)) {
      registry = parsed;
    } else {
      registry = {};
    }
  } catch (err) {
    console.error("[protected-files] Failed to load registry:", err.message);
  }
}

function saveRegistry() {
  writeFileSync(REGISTRY_PATH, JSON.stringify(registry, null, 2) + "\n", "utf-8");
}

/**
 * Regenerate the hookify .md pattern from current registry keys.
 * Groups by directory prefix for cleaner regex, e.g.:
 *   data/nicu/(file1|file2|file3)
 * Falls back to full-path alternation for mixed directories.
 */
function regenerateHookflow() {
  const paths = Object.keys(registry);
  if (paths.length === 0) return;

  // Normalize all to forward slash
  const normalized = paths.map((p) => p.replace(/\\/g, "/"));

  // Group by directory
  const groups = {};
  for (const p of normalized) {
    const lastSlash = p.lastIndexOf("/");
    const dir = lastSlash >= 0 ? p.slice(0, lastSlash) : "";
    const file = lastSlash >= 0 ? p.slice(lastSlash + 1) : p;
    if (!groups[dir]) groups[dir] = [];
    groups[dir].push(file);
  }

  // Build regex: if single directory group, use dir/(file1|file2), else alternation
  const dirKeys = Object.keys(groups);
  let pattern;
  if (dirKeys.length === 1 && dirKeys[0]) {
    const dir = dirKeys[0];
    const files = groups[dir].map((f) => escapeRegex(f)).join("|");
    pattern = `${escapeRegex(dir)}/(${files})`;
  } else {
    pattern = normalized.map((p) => escapeRegex(p)).join("|");
  }

  const md = `---
name: Block edits to governed data files
description: >
  Blocks edit/create on files registered in data/protected-files.json.
  Pattern is auto-regenerated by the protected-files extension when the registry changes.
  Do NOT manually edit this file — use add_protected_file / remove_protected_file tools.
event: file
action: block
lifecycle: pre
pattern: '${pattern}'
---

🚫 **BLOCKED: This file is governed by dedicated extension tools.**

This data file is protected by the data governance system. Direct \`edit\` and \`create\` calls are not allowed.

**What to do instead:**
1. Check the protected-files registry (\`data/protected-files.json\`) for the specific tool instructions
2. Use the dedicated extension tools mentioned in the registry entry for this file
3. \`view\` (read) is still allowed for context — only writes are blocked

**If you need to add/remove files from protection:**
- Use \`add_protected_file\` to register a new governed file
- Use \`remove_protected_file\` to unregister a file

The pattern in this hookflow is auto-generated. Do NOT edit it manually.
`;

  writeFileSync(HOOKFLOW_PATH, md, "utf-8");
}

function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// Initial load + hookflow sync
loadRegistry();
regenerateHookflow();

// Hot-reload on change
if (existsSync(REGISTRY_PATH)) {
  watchFile(REGISTRY_PATH, { interval: 5000 }, () => {
    loadRegistry();
    regenerateHookflow();
  });
}

// ── Path matching ───────────────────────────────────────────────────────────

/**
 * Check if a given absolute or relative path matches any protected file.
 * Handles both forward-slash and backslash paths, absolute and relative.
 * Returns the denial message if protected, or null if not.
 */
function checkProtected(filePath) {
  if (!filePath || typeof filePath !== "string") return null;

  // Normalize the path for comparison
  const normalized = filePath.replace(/\\/g, "/");

  for (const [protectedPath, message] of Object.entries(registry)) {
    const normalizedProtected = protectedPath.replace(/\\/g, "/");

    // Match: exact relative path, or absolute path ending with the relative path
    if (
      normalized === normalizedProtected ||
      normalized.endsWith("/" + normalizedProtected) ||
      normalized.endsWith("\\" + normalizedProtected)
    ) {
      return message;
    }
  }

  return null;
}

// ── Hook implementation ─────────────────────────────────────────────────────

function buildDenialContext(toolName, filePath, message) {
  return [
    `🚫 BLOCKED: \`${toolName}\` on protected file \`${filePath}\``,
    "",
    message,
    "",
    "Protected files are governed by dedicated extension tools that validate input,",
    "enforce schema, and handle side effects. Use the tools mentioned above instead.",
    "",
    "Reading (view) is still allowed for context — only writes are blocked.",
  ].join("\n");
}

// ── Tool definitions ─────────────────────────────────────────────────────────

const tools = [
  {
    name: "add_protected_file",
    description:
      "Register a data file as protected. Once registered, direct edit/create calls " +
      "on this file will be blocked by the hookflow engine. The denial message should " +
      "tell agents which extension tools to use instead.",
    parameters: {
      type: "object",
      properties: {
        file_path: {
          type: "string",
          description:
            "Relative path from repo root (forward slashes), e.g. 'data/finance/budget.db'",
        },
        denial_message: {
          type: "string",
          description:
            "Message shown when blocked — should name the specific tools to use instead",
        },
      },
      required: ["file_path", "denial_message"],
    },
    execute: async ({ file_path, denial_message }) => {
      const normalized = file_path.replace(/\\/g, "/");
      registry[normalized] = denial_message;
      saveRegistry();
      regenerateHookflow();
      return `✅ Protected: \`${normalized}\`\nHookflow pattern updated. The file is now governed.`;
    },
  },
  {
    name: "remove_protected_file",
    description:
      "Remove a file from the protected registry. Direct edits will be allowed again.",
    parameters: {
      type: "object",
      properties: {
        file_path: {
          type: "string",
          description: "Relative path to unprotect, e.g. 'data/nicu/pumping-log.json'",
        },
      },
      required: ["file_path"],
    },
    execute: async ({ file_path }) => {
      const normalized = file_path.replace(/\\/g, "/");
      if (!(normalized in registry)) {
        return `⚠️ \`${normalized}\` is not in the protected registry.`;
      }
      delete registry[normalized];
      saveRegistry();
      regenerateHookflow();
      return `✅ Unprotected: \`${normalized}\`\nHookflow pattern updated. Direct edits are now allowed.`;
    },
  },
  {
    name: "list_protected_files",
    description: "List all currently protected files and their denial messages.",
    parameters: { type: "object", properties: {} },
    execute: async () => {
      const entries = Object.entries(registry);
      if (entries.length === 0) return "No files currently protected.";
      const lines = entries.map(
        ([path, msg]) => `• **${path}**\n  ${msg}`
      );
      return `📋 Protected files (${entries.length}):\n\n${lines.join("\n\n")}`;
    },
  },
];

// ── Join Session ────────────────────────────────────────────────────────────

await joinSession({
  tools,
  hooks: {
    onPreToolUse: async (input) => {
      // Only intercept edit and create
      if (input.toolName !== "edit" && input.toolName !== "create") return;

      const filePath = input.toolArgs?.path;
      const denial = checkProtected(filePath);

      if (denial) {
        return {
          permissionDecision: "deny",
          permissionDecisionReason: buildDenialContext(input.toolName, filePath, denial),
        };
      }
    },

    onPostToolUse: async (input) => {
      // Only intercept edit and create
      if (input.toolName !== "edit" && input.toolName !== "create") return;

      const filePath = input.toolArgs?.path;
      const denial = checkProtected(filePath);

      if (denial) {
        return {
          additionalContext: buildDenialContext(input.toolName, filePath, denial),
        };
      }
    },

    onSessionStart: async () => {
      const fileCount = Object.keys(registry).length;
      if (fileCount === 0) return;

      return {
        additionalContext: [
          `[protected-files] Extension loaded — ${fileCount} file(s) are governed by dedicated tools.`,
          "Attempts to `edit` or `create` these files will be denied with instructions for the correct tool.",
          "`view` is still allowed for reading context.",
        ].join(" "),
      };
    },
  },
});
